spring:
  application:
    name: ogsestudo
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
    baseline-on-migrate: false
  jpa:
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow